CC = gcc
CFLAGS = -Wall -Wextra -Wno-unused-parameter

SOURCES = noticia.c
HEADERS = noticia.h

PUBLICADOR = publicador
SUSCRIPTOR = suscriptor
SISTEMA_PUB_SUB = sistema_pub_sub

PUBLICADOR_SOURCES = $(SOURCES) publicador.c
SUSCRIPTOR_SOURCES = $(SOURCES) suscriptor.c
SISTEMA_PUB_SUB_SOURCES = $(SOURCES) sistemaComunicaciones.c

all: $(PUBLICADOR) $(SUSCRIPTOR) $(SISTEMA_PUB_SUB)

$(PUBLICADOR): $(PUBLICADOR_SOURCES) $(HEADERS)
	$(CC) $(CFLAGS) -o $(PUBLICADOR) $(PUBLICADOR_SOURCES)

$(SUSCRIPTOR): $(SUSCRIPTOR_SOURCES) $(HEADERS) 
	$(CC) $(CFLAGS) -o $(SUSCRIPTOR) $(SUSCRIPTOR_SOURCES)

$(SISTEMA_PUB_SUB): $(SISTEMA_PUB_SUB_SOURCES) $(HEADERS)
	$(CC) $(CFLAGS) -o $(SISTEMA_PUB_SUB) $(SISTEMA_PUB_SUB_SOURCES)

clean:
	rm -f $(PUBLICADOR) $(SUSCRIPTOR) $(SISTEMA_PUB_SUB)

.PHONY: all clean